# Use postgres/example user/password credentials
version: '3.1'
services:
  simplebank-db:
    image: postgres:12-alpine
    ports:
      - 9595:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
